version: 0.2

env:
  variables:
    ECR_REPOSITORY: "540731803504.dkr.ecr.us-east-1.amazonaws.com/go/hello-http" # Replace with yours

phases:
  install:
    runtime-variables:
      GOPROXY: "https://proxy.golang.org,direct"
    commands:
      - echo "Installing Go 1.24.5"
      - curl -LO https://golang.org/dl/go1.24.5.linux-amd64.tar.gz
      - sudo tar -C /usr/local -xzf go1.24.5.linux-amd64.tar.gz
      - export PATH=/usr/local/go/bin:$PATH
      - go version

  build:
    commands:
      - echo $PWD
      - cd cicd_test/src
      - go build -o app .
      - echo "Building Docker image..."
      - docker build -t $ECR_REPOSITORY:latest .

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_REPOSITORY:latest
      - docker push $ECR_REPOSITORY:$CODEBUILD_BUILD_NUMBER
      - cd ../..
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $ECR_REPOSITORY:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
artifacts:
    files: imagedefinitions.json